### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by spekary** [tj-actions/coverage-badge-go#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

In your doc, you are using the wrong id for verify-changes:

        if: steps.changed_files.outputs.files_changed == 'true'

Should be:

        if: steps.verify-changed-files.outputs.files_changed == 'true'

### To Reproduce

See doc

### What OS are you seeing the problem on?

all

### Expected behavior?

        if: steps.verify-changed-files.outputs.files_changed == 'true'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@spekary Thanks for the call out this should be fixed now, don’t forget to star this project to help us reach others.
