### ISSUE TITLE
[BUG] <why my badge generated not in % form> 

### ISSUE THREAD

**Issue by mtcoafun** [tj-actions/coverage-badge-go#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

why my badge generated not in % form

<img width="108" alt="image" src="https://user-images.githubusercontent.com/50589627/156921896-2931608f-2ee0-4e0b-b17b-999097497392.png">

### To Reproduce

use your .yml

### What OS are you seeing the problem on?

all

### Expected behavior?

become % form.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Related to #46 the README has been updated
