### ISSUE TITLE
[BUG] <cannot use -o flag with multiple packages>

### ISSUE THREAD

**Issue by mtcoafun** [tj-actions/coverage-badge-go#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

when use the yml file you provide, workflow will exit with this message

<img width="902" alt="image" src="https://user-images.githubusercontent.com/50589627/156922084-2fe1397b-1154-4ef3-96f3-f65c0f2b71bc.png">

### To Reproduce

when i change go version to 1.17, error will disappear.

### What OS are you seeing the problem on?

all

### Expected behavior?

fix this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@mtcoafun Seems there was a missing `|` in the sample action in the README that should be fixed now.
